---
plugin: openapi
specFile: petstore.yaml

security:
  # no requests permitted by default
  default: Deny

  # only requests meeting these conditions are permitted
  conditions:
    - effect: Permit
      requestHeaders:
        Authorization: s3cr3t
