name: CI
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      AWS_REGION: "eu-west-1"
      TESTCONTAINERS_RYUK_DISABLED: "true"
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Disable gradle daemon
        run: |
          mkdir -p ~/.gradle
          echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties

      - name: Test
        run: ./gradlew test --info --stacktrace

      - name: Build JARs
        if: ${{ startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/develop' }}
        run: ./gradlew shadowJar --info --stacktrace

      - name: Publish maven artifacts
        if: ${{ startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/develop' }}
        run: ./gradlew publish --info --stacktrace
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build and push beta Docker image
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: |
          chmod +x ./scripts/*.sh
          IMAGE_TAG_NAME="$( ./scripts/branch-to-tag-name.sh develop )"
          if [[ ! -z ${IMAGE_TAG_NAME} ]]; then
            ./scripts/docker-build.sh "${IMAGE_TAG_NAME}"
          fi
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push versioned release Docker tags
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          chmod +x ./scripts/*.sh
          CURRENT_VERSION="$( git describe --tags --exact-match )"
          if [[ "${CURRENT_VERSION:0:1}" == "v" ]]; then
          	CURRENT_VERSION="$( echo ${CURRENT_VERSION} | cut -c 2- )"
          fi
          ./scripts/docker-build.sh "${CURRENT_VERSION}"
          ./scripts/docker-build.sh "latest"
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Release versioned JAR
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/github-script@v5
        with:
          script: |
            const script = require('./.github/github-release.js')
            await script({github, context})
